title = "configuration of mirrors-os"

[global]
server = "127.0.0.1:52111"
logdir = "./log"

[archlinux]
name = "archlinux"
srcroot = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinux/"
src = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinux/"
exclusion = ["iso/","testing/"]
cookie = "TEAMBITION_SESSIONID=xxx; TEAMBITION_SESSIONID.sig=xxx"
base = "mirrors/"
dbpath = "archlinux.db"
cron = "0 0 0,12 * * *"

[archlinuxcn]
name = "archlinuxcn"
srcroot = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/"
src = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/"
exclusion = []
cookie = "TEAMBITION_SESSIONID=xxx; TEAMBITION_SESSIONID.sig=xxx"
base = "mirrors/"
dbpath = "archlinuxcn.db"
cron = "0 0 6,18 * * *"
