title = "configuration of mirrors-os"

[global]
server = "127.0.0.1:52111"

[archlinux]
src = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinux/"
cookie = "TEAMBITION_SESSIONID=xxx; TEAMBITION_SESSIONID.sig=xxx"
base = "mirrors/"
dbpath = "archlinux.db"
cron = "0 0 0,12 * * *"

[archlinuxcn]
src = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/"
cookie = "TEAMBITION_SESSIONID=xxx; TEAMBITION_SESSIONID.sig=xxx"
base = "mirrors/"
dbpath = "archlinuxcn.db"
cron = "0 0 6,18 * * *"
